/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_DataSource */

#ifndef _Included_jni_DataSource
#define _Included_jni_DataSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_DataSource
 * Method:    alloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jni_DataSource_alloc
  (JNIEnv *, jobject);

/*
 * Class:     jni_DataSource
 * Method:    dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jni_DataSource_dealloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jni_DataSource
 * Method:    getIndex
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jni_DataSource_getIndex
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jni_DataSource
 * Method:    setIndex
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_jni_DataSource_setIndex
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     jni_DataSource
 * Method:    updateArrayIndex
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_jni_DataSource_updateArrayIndex
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     jni_DataSource
 * Method:    deleteIndex
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jni_DataSource_deleteIndex
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jni_DataSource
 * Method:    exportIndexList
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_jni_DataSource_exportIndexList
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
